sorter:
  default_source: ~/Downloads
  collision_policy: rename
  recursive_scan: false
  rules:
  - name: Sort Images
    target_folder: C:/Users/jonas/Desktop/test_sorting_area/sorted_images
    extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .heic
    - .webp
  - name: Sort Documents
    target_folder: C:/Users/jonas/Desktop/test_sorting_area/sorted_docs
    extensions:
    - .pdf
    - .docx
    - .pptx
    - .xlsx
    - .txt
    - .md
  ignore_patterns:
  - .DS_Store
  - Thumbs.db
  - __pycache__
scaffolder:
  templates_dir: ~/.tiedye/templates
  default_project_destination: ~/Desktop
  favorites: []
